Removendo linhas duplicadas

In [1]:

import pandas as pd

In [4]:
#Abrindo o arquivo em excel e colocando na variavel arquivo.
arquivo = "C:\\Users\\miche\\Desktop\\Codigos Python\Datasets\\Aluno.xlsx"

#Carregando o arquivo
xls = pd.ExcelFile(arquivo)

#Verificando as planilhas
print(xls.sheet_names)

['Plan1']

In [5]:
alunos = xls.parse('Plan1')

#fazendo a leitura do arquivo.
alunos

,Aluno,Data_Nascimento,Sexo,Nota_1_semestre,Nota_2_semestre,Nota_3_semestre,Nota_4_semestre
0,Rodolfo,2011-12-01,M,8,5,4,2
1,Paul,2000-01-07,M,9,6,10,9
2,Ronald,2001-05-30,M,5,4,8,9
3,Mateus,1999-07-20,M,10,3,6,3
4,Maria,2001-05-01,F,10,10,10,10
5,Paula,2000-12-25,F,9,10,5,10
6,Rodolfo,2011-12-01,M,8,5,4,2
7,Paul,2000-01-07,M,9,6,10,9

In [9]:
alunos.duplicated().head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [10]:
alunos.Aluno.duplicated().head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
Name: Aluno, dtype: bool

In [11]:
alunos.duplicated().sum()

2

In [12]:
#Para encontra a primeira ocorrência de repetição, começando do index 0.
alunos.loc[alunos.duplicated(keep='first'),:]

,Aluno,Data_Nascimento,Sexo,Nota_1_semestre,Nota_2_semestre,Nota_3_semestre,Nota_4_semestre
6,Rodolfo,2011-12-01,M,8,5,4,2
7,Paul,2000-01-07,M,9,6,10,9

In [13]:
#Para encontra a primeira ocorrência de repetição, começando do final do datafreme.
alunos.loc[alunos.duplicated(keep='last'),:]

,Aluno,Data_Nascimento,Sexo,Nota_1_semestre,Nota_2_semestre,Nota_3_semestre,Nota_4_semestre
0,Rodolfo,2011-12-01,M,8,5,4,2
1,Paul,2000-01-07,M,9,6,10,9

In [17]:

alunos.loc[alunos.duplicated(keep='first'),:]

,Aluno,Data_Nascimento,Sexo,Nota_1_semestre,Nota_2_semestre,Nota_3_semestre,Nota_4_semestre
6,Rodolfo,2011-12-01,M,8,5,4,2
7,Paul,2000-01-07,M,9,6,10,9

In [22]:

alunos.drop_duplicates(keep='first')
#Caso queira excluir no dataframe original se não só salvar o resultado do acima em uma nova variável.
#alunos.drop_duplicates(keep='first', inplace=True)

In [23]:
alunos

,Aluno,Data_Nascimento,Sexo,Nota_1_semestre,Nota_2_semestre,Nota_3_semestre,Nota_4_semestre
0,Rodolfo,2011-12-01,M,8,5,4,2
1,Paul,2000-01-07,M,9,6,10,9
2,Ronald,2001-05-30,M,5,4,8,9
3,Mateus,1999-07-20,M,10,3,6,3
4,Maria,2001-05-01,F,10,10,10,10
5,Paula,2000-12-25,F,9,10,5,10